---
# Firewall rules for application server
- name: Open HTTP and HTTPS ports for application server
  ansible.posix.firewalld:
    zone: public
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - http
    - https