version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    networks:
      - sportstore-network

  sportstore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sportstore
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_ENVIRONMENT=Production
      - ConnectionStrings__SqlDatabase=Server=sqlserver,1433;Database=SportStore;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    restart: always
    networks:
      - sportstore-network

volumes:
  sqlserver_data:

networks:
  sportstore-network:
    driver: bridge
